{% set version = "0.7.0" %}
{% set sha256 = "69a8dcb85acda20862bd2c52b97f9c5b5f0fbc23c73c2824460269d0622b0b20" %}
{% set name = "jupyter_dashboards" %}

package:
  name: {{ name }} 
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1002
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - {{ name.replace('_', '-') }} = jupyter_dashboards.extensionapp:main 

requirements:
  host:
    - python
    - setuptools
  run:
    - notebook
    - python
    - traitlets

test:
  imports:
    - {{ name }} 
  commands:
    - {{ name.replace('_', '-') }} --help
    - jupyter dashboards --help

about:
  home: http://github.com/jupyter-incubator/dashboards
  license: BSD 3-Clause 
  license_file: LICENSE.md
  summary: Jupyter Dashboards Layout Extension 
  doc_url: https://{{ name }}-layout.readthedocs.io
  dev_url: https://github.com/jupyter-incubator/dashboards

extra:
  recipe-maintainers:
    - ericdill
    - parente
