# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "wIVXWbnrrpmn0jLGoxLM0gAxKL77A+YbWiourEN29fl4vXOx4SS0fDNOoGPjOWf95G3ZXT/9EIGhrA7Ik/bAAgGQw0pEHkKWGTbIHdxVcm0nJWtpF2oxl+j9IBB6z7rqvErENevntKGJovH3Q2vWcpE5Y/qn21tKFMsKejE8ps8YvxJlOEH7e/BbrMPh6fWZjgokfzmy56cIaa1bkV5eroyDPPqeMnSgCaewiZMtvPqeZnA+3tW6nrpfPy2A21jpjL7J+frAljjQCEHtCbOvc2eR21JKP7PMs5lds8Wh/1Zts9Ze7AcZBXUdpzSA7ebuFKc/ALZLJqHEJ9jYoU4/rg2PI8ll+3XDFIvSX92mqzBAZnZsysASwOU+NgCIUd3IXj/ZEUAsBPgDRhxZNrOVAlGdwqGBfW+TUjUuKA9E7zNeQwZGYN5Mmy4JGGdvn2K9E3iUDhEgArCaEJT4IRxlORBn7On4Noljnk7M88KrXKPtGl8LKlDV6Pn+RyTpKew++xLZU8mh1md7JuS5LYq2OnASMPqfoFStbNAR7CkSJ82Gpsta39y738Z1sL+hCnrNWUo70TsaFcUVIUnwiNoA45NZCdnD2phXuoqzszhUfpIltjnLe2byMtoNeza+hZpnUYS2osDN+0mbB4dOcUmGXpvHAWMGXu37puXHaXiiXtQ="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
