appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: wIVXWbnrrpmn0jLGoxLM0gAxKL77A+YbWiourEN29fl4vXOx4SS0fDNOoGPjOWf95G3ZXT/9EIGhrA7Ik/bAAgGQw0pEHkKWGTbIHdxVcm0nJWtpF2oxl+j9IBB6z7rqvErENevntKGJovH3Q2vWcpE5Y/qn21tKFMsKejE8ps8YvxJlOEH7e/BbrMPh6fWZjgokfzmy56cIaa1bkV5eroyDPPqeMnSgCaewiZMtvPqeZnA+3tW6nrpfPy2A21jpjL7J+frAljjQCEHtCbOvc2eR21JKP7PMs5lds8Wh/1Zts9Ze7AcZBXUdpzSA7ebuFKc/ALZLJqHEJ9jYoU4/rg2PI8ll+3XDFIvSX92mqzBAZnZsysASwOU+NgCIUd3IXj/ZEUAsBPgDRhxZNrOVAlGdwqGBfW+TUjUuKA9E7zNeQwZGYN5Mmy4JGGdvn2K9E3iUDhEgArCaEJT4IRxlORBn7On4Noljnk7M88KrXKPtGl8LKlDV6Pn+RyTpKew++xLZU8mh1md7JuS5LYq2OnASMPqfoFStbNAR7CkSJ82Gpsta39y738Z1sL+hCnrNWUo70TsaFcUVIUnwiNoA45NZCdnD2phXuoqzszhUfpIltjnLe2byMtoNeza+hZpnUYS2osDN+0mbB4dOcUmGXpvHAWMGXu37puXHaXiiXtQ=}
conda_forge_output_validation: true
