travis:
  secure:
    BINSTAR_TOKEN: FLHXK1GbvNwU65SctTkbCy/RsNOJmiRJD0nYTbIdtcmg7HGGmUKANkW3yGk0v7ALkYSvZbexsBloeNFljkg3X4OIJ+aoQ2SCt+PWTltetWwRASiMDtSGRtwULi6IBNWcQ3hzlVYCYG9A8TZzXwWx9JmjxpsmEkpl2swoIaY0spI17AzjcpqG9TPT6DlxyWqhCkzYUSc29TZ/OyjWsiJ9SbB9foY3YMp2GRL4aUfjw/sF9k0mqhQdqA0+XxLKjItzagJ4PVnOD0eAun7LMC4HVMbLJtaYaOWuHiL/Mjr057Q8cGlGNZpFBTRdfKZomff1smAnr+Q51Gr4iYWlHD7LMaaT2MBvcW0Myn3SPTIy4Z7edZnp/T0cVv2epX8KRHwp+gwT0+SK3ja2Mx3zQoU2pMU0CnCZ5P0iMzy8Du5QXG7N2fFmpJvaHtOO7bFYKwSFcn3htiucVhHgt7hucXPwSUEKp7uixpqGMvPunXxvphOBj5js1tfcoROwIXgCKDszAppaCll6zcLyULLEkXoEHT/QzaOmQMVGoyZlExhJFSM0svwE0MpsoxEkGt5uOM00Aleht2JrmI9PL0Ke15cAlqXOhaBfvi/Z2Ps7z7rQQ3SXzX60U3z6JpaO31wNKvu7CQ1drIo1t01dbm6MhiSmPlXSDJTeLTzsRw7aDUf8sto=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
